version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: movieknight_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - sql_data:/var/lib/mysql
      - ./bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
  rest_api:
    build: './app'
    container_name: movieknight_rest_api
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8000:8000"
  web_fe:
    build: './web-fe'
    container_name: movieknight_fe
    depends_on:
      - rest_api
    ports:
      - "3000:3000"
    volumes:
      - ./web-fe:/app  # Mount the local source code directory
      - /app/node_modules  # Prevent overwriting node_modules
volumes:
  sql_data: