version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: movieknight_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: movieknight
      MYSQL_USER: movieknight_user
      MYSQL_PASSWORD: abc123
    ports:
      - "3306:3306"
    volumes:
      - sql_data:/var/lib/mysql
      - ./bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
  rest_api:
    build: './app'
    container_name: movieknight_rest_api
    ports:
      - "8000:8000"
volumes:
  sql_data: